/**
 * ODflow dashboard — composition root.
 *
 * This is the only file that knows about more than one component. Components
 * change state via core/store.js and never call each other; layers draw and
 * never touch the DOM outside the map. Everything they have to agree on is
 * wired here, once.
 *
 * All transit/speed/route figures come from the static JSON generated by
 * apps/backend/scripts/build_dashboard_data.py — see data/README.md.
 */

import './styles/tokens.css';
import './styles/base.css';
import './styles/primitives.css';

import { html, $ } from './core/dom.js';
import { state, subscribe } from './core/store.js';
import { onTheme } from './core/theme.js';
import { createMap, map, refreshBasemap, DEFAULT_CENTER } from './core/map.js';
import { data, loadCore, loadDestinations, loadStops } from './core/data.js';

import * as speed from './layers/speed.js';
import * as destinations from './layers/destinations.js';
import * as stops from './layers/stops.js';
import * as routes from './layers/routes.js';
import * as imported from './layers/imported.js';
import { cityBorderLayer, drawCityBorder, highlightAreas, clearHighlight } from './layers/boundary.js';

import { Header } from './components/Header/index.js';
import { KpiBar } from './components/KpiBar/index.js';
import { TimeFilter } from './components/TimeFilter/index.js';
import { LayerToggles } from './components/LayerToggles/index.js';
import { SpeedLegend } from './components/SpeedLegend/index.js';
import { AreaPanel } from './components/AreaPanel/index.js';
import { ImportPanel } from './components/ImportPanel/index.js';
import { StopPanel } from './components/StopPanel/index.js';
import { TimeBadge } from './components/TimeBadge/index.js';

// ── Shell ────────────────────────────────────────────────────────────────────
const root = document.getElementById('app');
const shell = html`
  <div class="shell" style="display:contents">
    <aside></aside>
    <div id="mapwrap"><div id="map"></div></div>
  </div>`;
root.appendChild(shell);

const aside = $(shell, 'aside');
const mapWrap = $(shell, '#mapwrap');
const mapEl = $(shell, '#map');

createMap(mapEl);

// ── Components ───────────────────────────────────────────────────────────────
const header = Header();
const kpis = KpiBar();
const timeBadge = TimeBadge();
// A line lit from a stop's chip row goes into the same route layer the sidebar
// drives, so the sidebar's list has to re-read which routes are active.
const stopPanel = StopPanel({ onRoutesChanged: () => areaPanel.renderRoutes() });

const areaPanel = AreaPanel({ onAreaChange: handleAreaChange });
const timeFilter = TimeFilter({ onReset: handleReset });
const layerToggles = LayerToggles();
const speedLegend = SpeedLegend();
const importPanel = ImportPanel({ dropTarget: mapWrap });

root.prepend(header.el);
mapWrap.prepend(kpis.el);
mapEl.append(timeBadge.el, stopPanel.el);

// Sidebar order is the order of work: pick an area, pick a time cut, choose
// what's drawn, read the ramp, bring your own layer.
aside.append(areaPanel.el, timeFilter.el, layerToggles.el, speedLegend.el, importPanel.el);

// ── Layer wiring ─────────────────────────────────────────────────────────────
cityBorderLayer.addTo(map);
speed.speedLayer.addTo(map);
routes.attachTo(map);

// A drawn line shows its own stops, wherever they are. They are the same station
// records the stop layer draws, so this only has to re-render that layer — and
// pull in the survey file first if nothing has needed it yet.
routes.onChange(() => {
  if (!data.stops) {
    loadStops()
      .then(() => { stops.render(); stops.syncVisibility(); layerToggles.renderStopsLegend(); })
      .catch(e => console.error('[Stops] failed to load for the drawn line:', e));
    return;
  }
  stops.render();
  stops.syncVisibility();
  layerToggles.renderStopsLegend();
  stopPanel.refresh();
});

stops.setSelectHandler(() => stopPanel.render());

// ── Reactions ────────────────────────────────────────────────────────────────

/** Restyle the network for the current cut and push the figures to the KPI strip. */
function refreshSpeed() {
  kpis.setSpeedStats(speed.recolor(), state.period);
  timeBadge.update(state);
}

function applyLayerVisibility() {
  speed.setVisible(state.layers);
  destinations.setVisible(state.layers.dest);
  stops.syncVisibility();
  layerToggles.syncPanels();

  if (state.layers.dest) {
    loadDestinations()
      .then(() => { layerToggles.renderCategories(); destinations.render(); })
      .catch(e => console.error('[Destinations] failed to load:', e));
  }

  // Two things put stops on the map: the toggle, and a drawn line bringing its
  // own. So the redraw is driven by whether anything will be drawn at all —
  // keying it to the toggle alone would leave a line's stops stale when the
  // toggle went off, and would close the panel on a stop still sitting on screen.
  if (state.layers.stops || routes.activeRoutes().length) {
    loadStops()
      .then(() => { stops.render(); layerToggles.renderStopsLegend(); refreshRidership(); })
      .catch(e => console.error('[Stops] failed to load:', e));
  } else {
    stopPanel.close();
  }
}

/**
 * Boardings for the current selection. The station list the map is drawing is
 * passed through whenever it's loaded, because neighbourhood catchments overlap
 * and only a per-station sum counts a shared border station once — see
 * KpiBar.setRidership.
 */
function refreshRidership() {
  // inArea, never visible: a drawn line's stops ignore the area filter on purpose,
  // and rolling them into a neighbourhood's boardings would credit it with stops
  // in another city.
  const stations = data.stops && state.areaRecords.length ? stops.stopsState.inArea : null;
  kpis.setRidership(state.areaRecords, data.stopTotals, stations);
}

subscribe((s, changed) => {
  if (changed.has('day') || changed.has('period')) {
    timeFilter.sync();
    refreshSpeed();
  }

  // The stop layer is classified on the selected window's boardings, so a period
  // step — including every tick of הרצת יום — has to redraw it. `day` is left out
  // on purpose: the station survey is a weekday average and has nothing to say
  // about א׳ vs ה׳, so redrawing on a day pill would only fake a change.
  if (changed.has('period') && data.stops) {
    stops.render();
    layerToggles.renderStopsLegend();
    stopPanel.refresh();
  }

  if (changed.has('layers')) applyLayerVisibility();

  if (changed.has('destCats') && data.destinations) destinations.render();

  if (changed.has('area')) {
    speed.computeMembership();
    kpis.setScope(s.areaName);
    refreshSpeed();
    if (data.destinations && s.layers.dest) destinations.render();
    if (data.stops) {
      stops.render();
      layerToggles.renderStopsLegend();
      stopPanel.refresh();
    }
    refreshRidership();

    // More than one neighbourhood picked and the station file not fetched yet:
    // its per-station figures are the only way to add up overlapping catchments
    // without double-counting, so pull it in even with the stop layer off.
    if (!data.stops && s.areaRecords.length > 1) {
      loadStops()
        .then(() => { stops.render(); refreshRidership(); })
        .catch(e => console.error('[Stops] failed to load for the area roll-up:', e));
    }
  }
});

/** The selection changed in the sidebar: move and outline the map. */
function handleAreaChange(neighs) {
  if (!neighs?.length) {
    clearHighlight();
    return;
  }
  const bounds = highlightAreas(neighs);
  if (bounds) map.fitBounds(bounds, { padding: [30, 30] });
}

/** Reset clears selections the TimeFilter doesn't own. */
function handleReset() {
  areaPanel.clearRoutes();
  map.setView(data.center || DEFAULT_CENTER, 15);
}

// A theme flip re-steps every palette. Layers styled at draw time have to be
// rebuilt or restyled; nothing here is a plain CSS swap.
onTheme(() => {
  refreshBasemap();
  speed.build();
  refreshSpeed();
  timeFilter.buildSpark();
  drawCityBorder(data.border);
  if (state.areaRecords.length) highlightAreas(state.areaRecords);
  routes.refresh();
  areaPanel.renderRoutes();
  imported.refresh();
  if (data.destinations) { layerToggles.renderCategories(); destinations.render(); }
  if (data.stops) {
    stops.render();
    layerToggles.renderStopsLegend();
    stopPanel.refresh();
  }
});

// ── Boot ─────────────────────────────────────────────────────────────────────
async function start() {
  kpis.setLoading();
  areaPanel.load();

  const { segmentsFailed } = await loadCore();

  drawCityBorder(data.border);
  if (data.center) map.setView(data.center, 13);

  speed.build();
  // The period pills and the sparkline are both the time axis kpis.json ships,
  // so neither can be drawn before loadCore has resolved.
  timeFilter.buildPeriods();
  timeFilter.buildSpark();
  refreshSpeed();
  refreshRidership();
  applyLayerVisibility();

  if (segmentsFailed) kpis.setSegmentError('שגיאת נתונים');
}

start().catch(e => {
  console.error('Dashboard failed to start', e);
  kpis.setSegmentError('שגיאת רשת');
});
