/**
 * ODflow dashboard — composition root.
 *
 * This is the only file that knows about more than one component. Components
 * change state via core/store.js and never call each other; layers draw and
 * never touch the DOM outside the map. Everything they have to agree on is
 * wired here, once.
 *
 * All transit/speed/route figures come from the static JSON generated by
 * apps/backend/scripts/build_dashboard_data.py — see data/README.md.
 */

import './styles/tokens.css';
import './styles/base.css';
import './styles/primitives.css';

import { html, $ } from './core/dom.js';
import { state, subscribe } from './core/store.js';
import { onTheme } from './core/theme.js';
import { createMap, map, refreshBasemap, DEFAULT_CENTER } from './core/map.js';
import { data, loadCore, loadDestinations, loadStops, loadRoads } from './core/data.js';

import * as speed from './layers/speed.js';
import * as destinations from './layers/destinations.js';
import * as stops from './layers/stops.js';
import * as routes from './layers/routes.js';
import * as imported from './layers/imported.js';
import * as roads from './layers/roads.js';
import { cityBorderLayer, drawCityBorder, highlightArea, clearHighlight } from './layers/boundary.js';

import { Header } from './components/Header/index.js';
import { KpiBar } from './components/KpiBar/index.js';
import { TimeFilter } from './components/TimeFilter/index.js';
import { LayerToggles } from './components/LayerToggles/index.js';
import { SpeedLegend } from './components/SpeedLegend/index.js';
import { AreaPanel } from './components/AreaPanel/index.js';
import { ImportPanel } from './components/ImportPanel/index.js';
import { StopPanel } from './components/StopPanel/index.js';
import { TimeBadge } from './components/TimeBadge/index.js';

// ── Shell ────────────────────────────────────────────────────────────────────
const root = document.getElementById('app');
const shell = html`
  <div class="shell" style="display:contents">
    <aside></aside>
    <div id="mapwrap"><div id="map"></div></div>
  </div>`;
root.appendChild(shell);

const aside = $(shell, 'aside');
const mapWrap = $(shell, '#mapwrap');
const mapEl = $(shell, '#map');

createMap(mapEl);

// ── Components ───────────────────────────────────────────────────────────────
const header = Header();
const kpis = KpiBar();
const timeBadge = TimeBadge();
const stopPanel = StopPanel();

const areaPanel = AreaPanel({ onAreaChange: handleAreaChange });
const timeFilter = TimeFilter({ onReset: handleReset });
const layerToggles = LayerToggles();
const speedLegend = SpeedLegend();
const importPanel = ImportPanel({ dropTarget: mapWrap });

root.prepend(header.el);
mapWrap.prepend(kpis.el);
mapEl.append(timeBadge.el, stopPanel.el);

// Sidebar order is the order of work: pick an area, pick a time cut, choose
// what's drawn, read the ramp, bring your own layer.
aside.append(areaPanel.el, timeFilter.el, layerToggles.el, speedLegend.el, importPanel.el);

// ── Layer wiring ─────────────────────────────────────────────────────────────
cityBorderLayer.addTo(map);
roads.roadsLayer.addTo(map);
roads.arrowLayer.addTo(map);
speed.speedLayer.addTo(map);
routes.attachTo(map);

map.on('zoomend', () => roads.onZoom());

stops.setSelectHandler(() => stopPanel.render());

// ── Reactions ────────────────────────────────────────────────────────────────

/** Restyle the network for the current cut and push the figures to the KPI strip. */
function refreshSpeed() {
  kpis.setSpeedStats(speed.recolor(), state.period);
  timeBadge.update(state);
}

function applyLayerVisibility() {
  speed.setVisible(state.layers);
  destinations.setVisible(state.layers.dest);
  stops.setVisible(state.layers.stops);
  roads.setVisible(state.layers.roads);
  layerToggles.syncPanels();

  if (state.layers.roads && !data.roads) {
    loadRoads()
      .then(geojson => {
        roads.build(geojson);
        roads.setVisible(state.layers.roads); // re-sync arrows after async build
      })
      .catch(e => console.error('[Roads] failed to load:', e));
  }

  if (state.layers.dest) {
    loadDestinations()
      .then(() => { layerToggles.renderCategories(); destinations.render(); })
      .catch(e => console.error('[Destinations] failed to load:', e));
  }

  if (state.layers.stops) {
    loadStops()
      .then(() => { stops.render(); layerToggles.renderStopsLegend(); })
      .catch(e => console.error('[Stops] failed to load:', e));
  } else {
    stopPanel.close();
  }
}

subscribe((s, changed) => {
  if (changed.has('day') || changed.has('period')) {
    timeFilter.sync();
    refreshSpeed();
  }

  if (changed.has('layers')) applyLayerVisibility();

  if (changed.has('destCats') && data.destinations) destinations.render();

  if (changed.has('area')) {
    speed.computeMembership();
    kpis.setScope(s.areaName);
    refreshSpeed();
    if (data.destinations && s.layers.dest) destinations.render();
    if (data.stops) {
      stops.render();
      layerToggles.renderStopsLegend();
      stopPanel.refresh();
    }
    kpis.setRidership(s.areaRecord, data.stopTotals);
  }
});

/** An area was picked (or cleared) in the sidebar: move and outline the map. */
function handleAreaChange(neigh) {
  if (!neigh) {
    clearHighlight();
    return;
  }
  const bounds = highlightArea(neigh);
  if (bounds) map.fitBounds(bounds, { padding: [30, 30] });
}

/** Reset clears selections the TimeFilter doesn't own. */
function handleReset() {
  areaPanel.clearRoutes();
  map.setView(data.center || DEFAULT_CENTER, 15);
}

// A theme flip re-steps every palette. Layers styled at draw time have to be
// rebuilt or restyled; nothing here is a plain CSS swap.
onTheme(() => {
  refreshBasemap();
  speed.build();
  refreshSpeed();
  timeFilter.buildSpark();
  drawCityBorder(data.border);
  if (state.areaRecord) highlightArea(state.areaRecord);
  routes.refresh();
  areaPanel.renderRoutes();
  imported.refresh();
  if (data.roads) roads.build(data.roads);
  if (data.destinations) { layerToggles.renderCategories(); destinations.render(); }
  if (data.stops) {
    stops.render();
    layerToggles.renderStopsLegend();
    stopPanel.refresh();
  }
});

// ── Boot ─────────────────────────────────────────────────────────────────────
async function start() {
  kpis.setLoading();
  areaPanel.load();

  const { segmentsFailed } = await loadCore();

  drawCityBorder(data.border);
  if (data.center) map.setView(data.center, 13);

  speed.build();
  timeFilter.buildSpark();
  refreshSpeed();
  kpis.setRidership(null, data.stopTotals);
  applyLayerVisibility();

  if (segmentsFailed) kpis.setSegmentError('שגיאת נתונים');
}

start().catch(e => {
  console.error('Dashboard failed to start', e);
  kpis.setSegmentError('שגיאת רשת');
});
